version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/server
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  logvolume01: {}